import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ModeButton } from './ui';
import { useI18n } from '../i18n';
export default function LegEditor({ leg, setLegField, }) {
    const { t } = useI18n();
    if (!leg)
        return null;
    return (_jsx("div", { className: "px-4 pb-4", children: _jsxs("div", { className: "rounded-xl border border-[var(--color-border)] p-3 bg-neutral-50 shadow-sm flex flex-wrap items-center gap-3", children: [_jsx("span", { className: "mr-1", children: t('legEditor.header') }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsxs(ModeButton, { active: leg.mode === 'plane', onClick: () => setLegField(leg.id, 'mode', 'plane'), children: [_jsx("span", { "aria-hidden": true, children: "\u2708\uFE0F" }), _jsx("span", { className: "sr-only", children: t('legEditor.plane') }), _jsx("span", { "aria-hidden": true, className: "max-w-0 opacity-0 overflow-hidden whitespace-nowrap group-hover:max-w-[120px] group-hover:opacity-100 transition-all duration-200 ease-out", children: t('legEditor.plane') })] }), _jsxs(ModeButton, { active: leg.mode === 'train', onClick: () => setLegField(leg.id, 'mode', 'train'), children: [_jsx("span", { "aria-hidden": true, children: "\uD83D\uDE86" }), _jsx("span", { className: "sr-only", children: t('legEditor.train') }), _jsx("span", { "aria-hidden": true, className: "max-w-0 opacity-0 overflow-hidden whitespace-nowrap group-hover:max-w-[120px] group-hover:opacity-100 transition-all duration-200 ease-out", children: t('legEditor.train') })] }), _jsxs(ModeButton, { active: leg.mode === 'bus', onClick: () => setLegField(leg.id, 'mode', 'bus'), children: [_jsx("span", { "aria-hidden": true, children: "\uD83D\uDE8C" }), _jsx("span", { className: "sr-only", children: t('legEditor.bus') }), _jsx("span", { "aria-hidden": true, className: "max-w-0 opacity-0 overflow-hidden whitespace-nowrap group-hover:max-w-[120px] group-hover:opacity-100 transition-all duration-200 ease-out", children: t('legEditor.bus') })] }), _jsxs(ModeButton, { active: leg.mode === 'car', onClick: () => setLegField(leg.id, 'mode', 'car'), children: [_jsx("span", { "aria-hidden": true, children: "\uD83D\uDE97" }), _jsx("span", { className: "sr-only", children: t('legEditor.car') }), _jsx("span", { "aria-hidden": true, className: "max-w-0 opacity-0 overflow-hidden whitespace-nowrap group-hover:max-w-[120px] group-hover:opacity-100 transition-all duration-200 ease-out", children: t('legEditor.car') })] })] }), _jsxs("label", { className: "inline-flex items-center gap-2 px-2 py-2 rounded-lg border border-[var(--color-border)] bg-white ml-auto", children: [_jsx("span", { children: t('legEditor.cost') }), _jsx("input", { type: "number", inputMode: "decimal", step: "any", min: 0, className: "w-28 bg-transparent outline-none", value: leg.cost || 0, onFocus: (e) => e.currentTarget.select(), onChange: (e) => setLegField(leg.id, 'cost', Number(e.target.value) || 0) })] })] }) }));
}
